<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <Platforms>AnyCPU</Platforms>
    <LangVersion>latest</LangVersion>
    <GameFolder>C:\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord</GameFolder>
  </PropertyGroup>

  <ItemGroup>
    <!-- Harmony Referansı (Atölyedeki Bannerlord.Harmony Modundan Alır) -->
    <!-- PrivateAssets/Private=False sayesinde çıkışa (bin) 0Harmony.dll kopyalanmaz -->
    <Reference Include="0Harmony">
      <HintPath>$(GameFolder)\..\..\workshop\content\261550\2859188632\bin\Win64_Shipping_Client\0Harmony.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <!-- TaleWorlds Temel Kütüphaneleri -->
    <Reference Include="TaleWorlds.CampaignSystem">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.CampaignSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="TaleWorlds.Core">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Core.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="TaleWorlds.Library">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Library.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="TaleWorlds.MountAndBlade">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.MountAndBlade.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="TaleWorlds.ObjectSystem">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.ObjectSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>

    <Reference Include="TaleWorlds.Localization">
      <HintPath>$(GameFolder)\bin\Win64_Shipping_Client\TaleWorlds.Localization.dll</HintPath>
      <Private>False</Private>
    </Reference>
    <Reference Include="TaleWorlds.SaveSystem">
      <HintPath>C:\Program Files (x86)\Steam\steamapps\common\Mount &amp; Blade II Bannerlord\bin\Win64_Shipping_Client\TaleWorlds.SaveSystem.dll</HintPath>
      <Private>False</Private>
    </Reference>
  </ItemGroup>

</Project>